### ISSUE TITLE
Update data & new features

### ISSUE THREAD

**Issue by pjastam** [Dato-Futbol/fifa-ranking#1]
I have a data update and some new features at [https://github.com/pjastam/fifa-ranking](https://github.com/pjastam/fifa-ranking). See it live in action at [https://pjastam.shinyapps.io/fifa-ranking/](https://pjastam.shinyapps.io/fifa-ranking/). Are you interested in a pull request so that you can integrate these changes to your original repo?

**Comment by Bustami** [comment]
Hey!
Sure, please go ahead with the pull request in order to merge it.

cheers
