### ISSUE TITLE
Missing team in the last update

### ISSUE THREAD

**Issue by lielv** [Dato-Futbol/fifa-ranking#6]
Great data thanks!

On the last update (19/09/2024) there are only 93 teams. I guess it's a script error (it didn't "open" the entire table)

**Comment by Bustami** [comment]
Hey!
Thanks for reporting the issue.
It's already solved [6916929](https://github.com/Dato-Futbol/fifa-ranking/commit/6916929cc8fbf3bc49a4d21a9670e5992e6a738b), adding the pending teams. 
As you said it was due a script error when scraping the data from the FIFA site.
